package com.gianlucaparadise.memorandaloco.constants

/**
 * Source of app list: https://www.xda-developers.com/google-apple-covid-19-contact-tracing-exposure-notifications-api-app-list-countries/
 * App List retrieved using: $(".table_wrapper,  td:nth-child(3)").map((index, element) => element.innerText.trim());
 */
val OFFICIAL_CONTACT_TRACING_APPS = listOf(
    "au.gov.dta.covidtrace",
    "at.roteskreuz.stopcorona",
    "be.sciensano.coronalert",
    "br.gov.datasus.guardioes",
    "egnc.moh.bruhealthtrace",
    "ca.gc.hcsc.canada.stopcovid",
    "hr.miz.evidencijakontakata",
    "cz.covid19cz.erouska.dev",
    "com.netcompany.smittestop_exposure_notification",
    "ec.gob.asi.android",
    "ee.tehik.hoia",
    "fi.thl.koronahaavi",
    "de.rki.coronawarnapp",
    "com.gha.covid.tracker",
    "com.covidtracker.hse",
    "it.ministerodellasalute.immuni",
    "jp.go.mhlw.covid19radar",
    "kz.nitec.bizbirgemiz",
    "ke.go.health_togethertrace",
    "lv.spkc.gov.apturicovid",
    "mt.gov.dp3t",
    "mx.gob.www",
    "nl.rijksoverheid.en",
    "net.hscni.covidtracker",
    "ph.staysafe.mobileapp",
    "pl.gov.mc.protegosafe",
    "fct.inesctec.stayaway",
    "sa.gov.nic.tabaud",
    "gov.scot.covidtracker",
    "si.gov.ostanizdrav",
    "za.gov.health.covidconnect",
    "es.gob.radarcovid",
    "ch.admin.bag.dp3t",
    "uk.nhs.covid19.production",
    "uy.gub.salud.plancovid19uy",
    "gov.adph.exposurenotifications",
    "gov.azdhs.covidwatch.android",
    "gov.michigan.MiCovidExposure",
    "gov.nv.dhhs.en",
    "gov.ny.health.proximity",
    "gov.nc.dhhs.exposurenotification",
    "gov.pa.covidtracker",
    "com.proudcrowd.exposure",
    "gov.vdh.exposurenotification",
    "org.cvkey.cvkey",
    "org.pathcheck.covidsafepathsbt.mn",
    "org.mitre.covidaware",
    "app.covidshield"
)